/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyIndexRouteImport } from './routes/journey/index'
import { Route as JourneyModuleIdRouteImport } from './routes/journey/$moduleId'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as PracticeTechniqueIdRouteImport } from './routes/practice/$techniqueId'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/journey/',
  path: '/journey/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyModuleIdRoute = JourneyModuleIdRouteImport.update({
  id: '/journey/$moduleId',
  path: '/journey/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTechniqueIdRoute = PracticeTechniqueIdRouteImport.update({
  id: '/practice/$techniqueId',
  path: '/practice/$techniqueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey/$moduleId': typeof JourneyModuleIdRoute
  '/practice/$techniqueId': typeof PracticeTechniqueIdRoute
  '/journey/': typeof JourneyIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/progress/': typeof ProgressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey/$moduleId': typeof JourneyModuleIdRoute
  '/practice/$techniqueId': typeof PracticeTechniqueIdRoute
  '/journey': typeof JourneyIndexRoute
  '/learn': typeof LearnIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/progress': typeof ProgressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journey/$moduleId': typeof JourneyModuleIdRoute
  '/practice/$techniqueId': typeof PracticeTechniqueIdRoute
  '/journey/': typeof JourneyIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/progress/': typeof ProgressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journey/$moduleId'
    | '/practice/$techniqueId'
    | '/journey/'
    | '/learn/'
    | '/practice/'
    | '/progress/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey/$moduleId'
    | '/practice/$techniqueId'
    | '/journey'
    | '/learn'
    | '/practice'
    | '/progress'
  id:
    | '__root__'
    | '/'
    | '/journey/$moduleId'
    | '/practice/$techniqueId'
    | '/journey/'
    | '/learn/'
    | '/practice/'
    | '/progress/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JourneyModuleIdRoute: typeof JourneyModuleIdRoute
  PracticeTechniqueIdRoute: typeof PracticeTechniqueIdRoute
  JourneyIndexRoute: typeof JourneyIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/': {
      id: '/journey/'
      path: '/journey'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$moduleId': {
      id: '/journey/$moduleId'
      path: '/journey/$moduleId'
      fullPath: '/journey/$moduleId'
      preLoaderRoute: typeof JourneyModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$techniqueId': {
      id: '/practice/$techniqueId'
      path: '/practice/$techniqueId'
      fullPath: '/practice/$techniqueId'
      preLoaderRoute: typeof PracticeTechniqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JourneyModuleIdRoute: JourneyModuleIdRoute,
  PracticeTechniqueIdRoute: PracticeTechniqueIdRoute,
  JourneyIndexRoute: JourneyIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
